### PR TITLE
Reenable strict mode so that shell gives helpful messages for unknown…

### PR DESCRIPTION
**Pull request by janedegtiareva**
… commands

### CODE REVIEW

**Comment by janedegtiareva** [comment]
fix for https://github.com/nearprotocol/near-shell/issues/50, which is a regression

**Comment by vgrichina** [comment]
AFAIK, this will break `near-shell` for cases when config is present, but given command doesn't accept all of the options in config.

**Comment by ilblackdragon** [comment]
@janedegtiareva  can we define `strict` only on the top commands? e.g. `near blah` fails but not `near send --blah=whatever`?

**Comment by janedegtiareva** [comment]
We can add all the config options to shell and expect no unrecognized config options. Opinions?

**Comment by mikedotexe** [comment]
> We can add all the config options to shell and expect no unrecognized config options. Opinions?

This is essentially the approach I took here:
https://github.com/nearprotocol/near-shell/pull/262

Plus some other fun snags to work through.

**Pull request closed without merging**
