### PR TITLE
Add Yargs default and middleware logic to display helpful message during invalid arg/command calls

### PR DESCRIPTION
**Pull request by mikedotexe**
Regarding #259 
[Followed this](https://github.com/yargs/yargs/blob/master/docs/advanced.md#default-commands) from the yargs documentation.

Added a couple of cases where an argument, command, and multiple commands are entered an not understood. Provides end user with simple feedback and instructions.

Screenshot 2020-02-03 11 52 01

**Update**: please see comments below regarding evolved approach

### CODE REVIEW

**Comment by vgrichina** [comment]
@mikedotexe see here https://github.com/nearprotocol/near-shell/issues/259#issuecomment-581564218, I think we should do it differently, so that arguments are also validated.

However feel free to merge it as a quick fix for now if full fix requires much more time.

**Comment by mikedotexe** [comment]
Hey folks, I have prefixed this PR with "WIP:" meaning work-in-progress. It's in a good state to start reviewing, I will make some minor changes.
So I am agreed that `strict()` will not work for us unless we change the config, which is possible but not ideal.
@vgrichina has the right idea of using middleware. A strange combination happens when there's middleware and a default command, both of which we need. The problem is that running `near` without arguments or commands no longer shows the full command list like it was when running `near --help`
This is [a pesky issue](https://github.com/yargs/yargs/issues/895).
I did not want to sacrifice this behavior, so I ripped out and modified some logic so that we'll still show all the commands and descriptions.
I also chained `.fail()` onto this with some minor error logging and suggestions.

Result:
`near` and `near --help` report the same screen (tiny difference is the word "near" appears in a different spot)
`near fake` » `Invalid command 'fake'`
`near fake --fakeArg hi` » `Invalid command 'fake'` `Invalid argument 'fakeArg`
`near call fake` » `Error: Not enough non-option arguments: got 1, need at least 2` `Please use the --help flag for more information.`
`near login fake` » `Invalid command 'fake'`

**Comment by vgrichina** [comment]
@mikedotexe the issue you linked seems to have a solution:

https://github.com/yargs/yargs/issues/895#issuecomment-392893305

any reason why we cannot use it? 

if there is bug in yargs, I'd prefer we fix it vs reimplementing half of the logic ourselves

**Comment by mikedotexe** [comment]
> @mikedotexe the issue you linked seems to have a solution:
> 
> [yargs/yargs#895 (comment)](https://github.com/yargs/yargs/issues/895#issuecomment-392893305)
> 
> any reason why we cannot use it?
> 
> if there is bug in yargs, I'd prefer we fix it vs reimplementing half of the logic ourselves

The comment you mentioned uses `strict()` which, as I understand will always throw for `contractName` and `walletUrl` that exists in `config.js`
I also don't like the idea of borrowing 54 lines of code from yargs, but having the commands there made it significantly better in my opinion. This is one of those cases where I was fighting the framework.

I think I'm now understanding Jane's comment better and will look into the approach.

**Comment by ilblackdragon** [comment]
What is the status with this PR?

**Comment by mikedotexe** [comment]
This approach becomes difficult with `near call` and `near view`. Closing in favor of https://github.com/nearprotocol/near-shell/pull/265

**Pull request closed without merging**
